# Generated by Django 4.2.5 on 2023-10-13 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0006_author_alter_book_slug_alter_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='lasst_name',
            new_name='last_name',
        ),
    ]
